downstream_package_name: python-nitrate
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-30-x86_64
    - fedora-31-x86_64
    - fedora-rawhide-x86_64
  trigger: pull_request
specfile_path: python-nitrate.spec
synced_files:
- python-nitrate.spec
- .packit.yaml
upstream_package_name: python-nitrate
