upstream_package_name: python-nitrate
downstream_package_name: python-nitrate

specfile_path: python-nitrate.spec
files_to_sync: [python-nitrate.spec]

actions:
  create-archive:
  - make tarball
  get-current-version:
  - make version

srpm_build_deps:
  - make
  - python3-docutils

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-all
  - epel-9
  - epel-8

- job: tests
  trigger: pull_request
  targets:
  - fedora-all
  - epel-9
  - epel-8

- job: copr_build
  trigger: commit
  branch: main
  targets:
  - fedora-all
  - epel-9
  - epel-8
  list_on_homepage: True
  preserve_project: True
  owner: psss
  project: python-nitrate
